In [1]:
from PattRecClasses import DiscreteD, GaussD, HMM, MarkovChain, GetPx
from matplotlib import pyplot as plt
import numpy as np

from matplotlib import pyplot as plt
from scipy.io import wavfile
from scipy.signal import firwin,filtfilt
from GetMusicFeatures import GetMusicFeatures
from FeatureExtractor import FeatureExtractor
import numpy as np
import pickle as pkl
def lowpass(x,fc,fs=44100):
    """ x is the signal, 
        fc is the cuttoff frequency expressed in Hz, must be between [0,fs/2]
    """
    b = firwin(1024, fc,fs=fs)
    y = filtfilt(b,1,x)
    return y

In [5]:
blues_all_feature_data = np.load('blues_all_feature_data.npy')
classical_all_feature_data = np.load('classical_all_feature_data.npy',allow_pickle=True)
for ff in range(len(classical_all_feature_data)):
    classical_all_feature_data[ff] = np.expand_dims(classical_all_feature_data[ff],axis=0)

reggae_all_feature_data = np.load('reggae_all_feature_data.npy',allow_pickle=True)
for ff in range(len(reggae_all_feature_data)):
    reggae_all_feature_data[ff] = np.expand_dims(reggae_all_feature_data[ff],axis=0)
    
disco_all_feature_data = np.load('disco_all_feature_data.npy',allow_pickle=True)
for ff in range(len(disco_all_feature_data)):
    disco_all_feature_data[ff] = np.expand_dims(disco_all_feature_data[ff],axis=0)


In [6]:
data_list = [blues_all_feature_data, 
            classical_all_feature_data, 
            disco_all_feature_data,
            reggae_all_feature_data]

In [7]:
q = np.array([0.1,0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.025])
A = np.array([[0.1,0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.025],[0.1,0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.025],[0.1,0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.025],[0.1,0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.025],[0.1,0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.025],[0.1,0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.025],[0.1,0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.025],[0.1,0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.025],[0.1,0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.025]])
mc = MarkovChain(q,A)

g1 = GaussD( means=[0], stdevs=[1] )   # Distribution for state = 1
g2 = GaussD( means=[10], stdevs=[2] )  # Distribution for state = 2
g3 = GaussD( means=[4], stdevs=[10])   # Distribution for state = 3
g4 = GaussD( means=[0], stdevs=[1])   # Distribution for state = 4
g5 = GaussD( means=[0], stdevs=[1] )   # Distribution for state = 1
g6 = GaussD( means=[10], stdevs=[2] )  # Distribution for state = 2
g7 = GaussD( means=[4], stdevs=[10])   # Distribution for state = 3
g8 = GaussD( means=[0], stdevs=[1])   # Distribution for state = 4
g9 = GaussD( means=[0], stdevs=[1])   # Distribution for state = 4
blues_h  = HMM( mc, [g1, g2, g3, g4, g5, g6, g7, g8, g9]) 

q2 = np.array([0.1,0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.025])
A2 = np.array([[0.1,0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.025],[0.1,0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.025],[0.1,0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.025],[0.1,0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.025],[0.1,0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.025],[0.1,0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.025],[0.1,0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.025],[0.1,0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.025],[0.1,0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.025]])
mc2 = MarkovChain(q2,A2)

g12 = GaussD( means=[0], stdevs=[1] )   # Distribution for state = 1
g22 = GaussD( means=[10], stdevs=[2] )  # Distribution for state = 2
g32 = GaussD( means=[4], stdevs=[10])   # Distribution for state = 3
g42 = GaussD( means=[0], stdevs=[1])   # Distribution for state = 4
g52 = GaussD( means=[0], stdevs=[1] )   # Distribution for state = 1
g62 = GaussD( means=[10], stdevs=[2] )  # Distribution for state = 2
g72 = GaussD( means=[4], stdevs=[10])   # Distribution for state = 3
g82 = GaussD( means=[0], stdevs=[1])   # Distribution for state = 4
g92 = GaussD( means=[10], stdevs=[1])   # Distribution for state = 4
classical_h = HMM( mc2, [g12, g22, g32, g42, g52, g62, g72, g82, g92]) 

# q3 = np.array([0.1,0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.025])
# A3 = np.array([[0.1,0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.025],[0.1,0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.025],[0.1,0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.025],[0.1,0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.025],[0.1,0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.025],[0.1,0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.025],[0.1,0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.025],[0.1,0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.025],[0.1,0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.025]])
# mc3 = MarkovChain(q3,A3)

# g13 = GaussD( means=[0], stdevs=[1] )   # Distribution for state = 1
# g23 = GaussD( means=[10], stdevs=[2] )  # Distribution for state = 2
# g33 = GaussD( means=[4], stdevs=[10])   # Distribution for state = 3
# g43 = GaussD( means=[0], stdevs=[1])   # Distribution for state = 4
# g53 = GaussD( means=[0], stdevs=[1] )   # Distribution for state = 1
# g63 = GaussD( means=[10], stdevs=[2] )  # Distribution for state = 2
# g73 = GaussD( means=[4], stdevs=[10])   # Distribution for state = 3
# g83 = GaussD( means=[0], stdevs=[1])   # Distribution for state = 4
# g93 = GaussD( means=[10], stdevs=[1])   # Distribution for state = 4
# country_h = HMM( mc3, [g13, g23, g33, g43, g53, g63, g73, g83, g93]) 

q4 = np.array([0.1,0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.025])
A4 = np.array([[0.1,0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.025],[0.1,0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.025],[0.1,0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.025],[0.1,0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.025],[0.1,0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.025],[0.1,0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.025],[0.1,0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.025],[0.1,0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.025],[0.1,0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.025]])
mc4 = MarkovChain(q4,A4)

g14 = GaussD( means=[0], stdevs=[1] )   # Distribution for state = 1
g24 = GaussD( means=[10], stdevs=[2] )  # Distribution for state = 2
g34 = GaussD( means=[4], stdevs=[10])   # Distribution for state = 3
g44 = GaussD( means=[0], stdevs=[1])   # Distribution for state = 4
g54 = GaussD( means=[0], stdevs=[1] )   # Distribution for state = 1
g64 = GaussD( means=[10], stdevs=[2] )  # Distribution for state = 2
g74 = GaussD( means=[4], stdevs=[10])   # Distribution for state = 3
g84 = GaussD( means=[0], stdevs=[1])   # Distribution for state = 4
g94 = GaussD( means=[100], stdevs=[1])   # Distribution for state = 4
disco_h = HMM( mc4, [g14, g24, g34, g44, g54, g64, g74, g84, g94]) 

q5 = np.array([0.1,0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.025])
A5 = np.array([[0.1,0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.025],[0.1,0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.025],[0.1,0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.025],[0.1,0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.025],[0.1,0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.025],[0.1,0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.025],[0.1,0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.025],[0.1,0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.025],[0.1,0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.025]])
mc5 = MarkovChain(q5,A5)

g15 = GaussD( means=[0], stdevs=[1] )   # Distribution for state = 1
g25 = GaussD( means=[10], stdevs=[2] )  # Distribution for state = 2
g35 = GaussD( means=[4], stdevs=[10])   # Distribution for state = 3
g45 = GaussD( means=[0], stdevs=[1])   # Distribution for state = 4
g55 = GaussD( means=[0], stdevs=[1] )   # Distribution for state = 1
g65 = GaussD( means=[10], stdevs=[2] )  # Distribution for state = 2
g75 = GaussD( means=[4], stdevs=[10])   # Distribution for state = 3
g85 = GaussD( means=[0], stdevs=[1])   # Distribution for state = 4
g95 = GaussD( means=[100], stdevs=[1])   # Distribution for state = 4
reggae_h = HMM( mc5, [g15, g25, g35, g45, g55, g65, g75, g85, g95]) 

HMM_list = [blues_h, classical_h, disco_h, reggae_h]

In [8]:
def cross_validation(HMM_list, data_list, K_number):
       
    class_number = len(HMM_list)
    
    number_data_per_chuck = int(80/K_number)
    
    confusion_matrix_list = []
    
    for K in range(K_number): #K_number fold crossvalidation 每次的train和test list都不一样   
        
        print('K:',K)
        ###############create train_list and test_list per K_fold Test##################
        train_list = []
        test_list = []
        for index in range(class_number):
            train_set = []
            test_set = []
            for loop in range(80):
                if loop not in range(number_data_per_chuck*K,number_data_per_chuck*(K+1)):
                    train_set.append(data_list[index][loop])
                else:
                    test_set.append(data_list[index][loop])
            train_list.append(train_set)
            test_list.append(test_set)
#         print(len(train_list[0]))
#         print(len(test_list[0]))
            
        ###############train HMM##################        
        for index in range(class_number):
            HMM_list[index].train(train_list[index],len(train_list[index]))
        
        ###############test each song in test_set##################
        confusion_matrix = np.zeros([class_number,class_number])
        
        for index in range(class_number):
            true_label = index
            
            for each_song in test_list[index]:  ###有100/K_number首
                
                prob_list = []

                for HMM_index in range(class_number):
                    logprob = HMM_list[HMM_index].logprob(each_song)
                    prob_list.append(logprob)

                classification_result = prob_list.index(max(prob_list))
                confusion_matrix[true_label,classification_result] += 1
                
        print(confusion_matrix)
        confusion_matrix_list.append(confusion_matrix)
    
    
    return confusion_matrix_list

In [9]:
K_number = 4
confusion_matrix_list = cross_validation(HMM_list, data_list, K_number)

K: 0
logprob: -1902.5158461936715  ite: 1
logprob: -1651.3873560151058  ite: 2
logprob: -1657.9462080940177  ite: 3
prob_change: -6.558852078911968 terminate after ite: 3
logprob: -4103.797178624023  ite: 1
logprob: -4117.547776466155  ite: 2
prob_change: -13.750597842131356 terminate after ite: 2
logprob: -2783.9368035503508  ite: 1
logprob: -2629.2994258092285  ite: 2
logprob: -2629.306768635023  ite: 3
prob_change: -0.007342825794694363 terminate after ite: 3
logprob: -3155.3924874592094  ite: 1
logprob: -3231.2312314433393  ite: 2
prob_change: -75.8387439841299 terminate after ite: 2
[[ 1. 12.  4.  3.]
 [ 2. 15.  3.  0.]
 [ 4.  3. 13.  0.]
 [ 0.  6. 14.  0.]]
K: 1
logprob: -1890.8857678125864  ite: 1
logprob: -1885.565388352351  ite: 2
logprob: -1886.4065487115113  ite: 3
prob_change: -0.8411603591603125 terminate after ite: 3
logprob: -4103.598442170277  ite: 1
logprob: -4103.594282154296  ite: 2
prob_change: 0.004160015981142351 terminate after ite: 2
logprob: -2629.7417322414562

In [10]:
aa = np.zeros([4,4])
for i in range(len(confusion_matrix_list)):
    aa += confusion_matrix_list[i]
aa

array([[ 7., 25., 26., 22.],
       [ 4., 39., 10., 27.],
       [ 7., 18., 50.,  5.],
       [25., 15., 26., 14.]])

In [11]:
class_number = 4

confusion_matrix = np.zeros([class_number,class_number])

for index in range(class_number):
    true_label = index

    for each_song in data_list[index][80:]:  ###有100/K_number首

        prob_list = []

        for HMM_index in range(class_number):
            logprob = HMM_list[HMM_index].logprob(each_song)
            prob_list.append(logprob)

        classification_result = prob_list.index(max(prob_list))
        confusion_matrix[true_label,classification_result] += 1

print(confusion_matrix)

[[ 7.  2.  7.  4.]
 [ 1.  9.  5.  5.]
 [ 2.  0. 13.  5.]
 [ 4.  6.  6.  4.]]


In [12]:
aa = np.zeros([4,4])
for i in range(len(confusion_matrix_list)):
    aa += confusion_matrix_list[i]
aa+=confusion_matrix
aa

array([[14., 27., 33., 26.],
       [ 5., 48., 15., 32.],
       [ 9., 18., 63., 10.],
       [29., 21., 32., 18.]])

In [14]:
for i in range(9):
    print(HMM_list[3].outputDistr[i].means)

[10.4896127]
[5.25210764]
[-39.49610676]
[-0.11898674]
[-0.11898674]
[5.25210764]
[-39.49610676]
[-0.11898674]
[100]


In [15]:
print(np.round(HMM_list[2].stateGen.A,2))

[[0.   0.   0.5  0.   0.   0.   0.5  0.   0.  ]
 [0.   0.35 0.15 0.   0.   0.35 0.15 0.   0.  ]
 [0.   0.03 0.47 0.   0.   0.03 0.47 0.   0.  ]
 [0.   0.   0.5  0.   0.   0.   0.5  0.   0.  ]
 [0.   0.   0.5  0.   0.   0.   0.5  0.   0.  ]
 [0.   0.35 0.15 0.   0.   0.35 0.15 0.   0.  ]
 [0.   0.03 0.47 0.   0.   0.03 0.47 0.   0.  ]
 [0.   0.   0.5  0.   0.   0.   0.5  0.   0.  ]
 [0.1  0.12 0.12 0.12 0.12 0.12 0.12 0.12 0.02]]
